/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;

/**
 *
 * @author adamg
 */
public class GUI_Obrazovka extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Obrazovka
     */
    public GUI_Obrazovka() {
        initComponents();
    }
    
    public void vyhodnotSpravne(){
        vysledok.setText("OK!");
        vysledok.setForeground(Color.GREEN);
    }
    
    public void vyhodnotNespravne(){
        vysledok.setText("NG!");
        vysledok.setForeground(Color.RED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        retazec = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textKontrola = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnKontrola = new javax.swing.JButton();
        vysledok = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Regex reťazec");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        retazec.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(retazec, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 540, 50));

        textKontrola.setColumns(20);
        textKontrola.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textKontrola.setRows(5);
        jScrollPane1.setViewportView(textKontrola);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 550, 280));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Text na kontrolu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        btnKontrola.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnKontrola.setText("Skontrolovať");
        btnKontrola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnKontrolaMouseReleased(evt);
            }
        });
        jPanel1.add(btnKontrola, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 190, 80));

        vysledok.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jPanel1.add(vysledok, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 700, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKontrolaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKontrolaMouseReleased
        if(retazec.getText().isEmpty()){
            vysledok.setText("");
            JOptionPane.showMessageDialog(this, "Nezadaný reťazec!", "Chyba", JOptionPane.ERROR_MESSAGE);
        }
        else if (textKontrola.getText().isEmpty()){
            vysledok.setText("");
            JOptionPane.showMessageDialog(this, "Nezadaný text na kontrolu!", "Chyba", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                // podľa : https://stackoverflow.com/questions/2704857/how-to-check-if-a-given-regex-is-valid
                Pattern.compile(retazec.getText());
                
                boolean vysledok = textKontrola.getText().matches(retazec.getText());
                
                if(vysledok){
                    vyhodnotSpravne();
                }
                else{
                    vyhodnotNespravne();
                }

            }catch(PatternSyntaxException exception){
                vysledok.setText("");
                JOptionPane.showMessageDialog(this, "Zadaný regex nie je platný", "Chyba", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnKontrolaMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Obrazovka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Obrazovka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Obrazovka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Obrazovka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Obrazovka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKontrola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField retazec;
    private javax.swing.JTextArea textKontrola;
    private javax.swing.JLabel vysledok;
    // End of variables declaration//GEN-END:variables
}
